<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="groovy.database.DatabaseConnectionTest" tests="4" skipped="0" failures="0" errors="0" timestamp="2025-04-14T01:53:57" hostname="pcosta-idea330" time="1.282">
  <properties/>
  <testcase name="deve criar uma fábrica de conexão corretamente" classname="groovy.database.DatabaseConnectionTest" time="0.101"/>
  <testcase name="deve estabelecer uma conexão com o banco de dados" classname="groovy.database.DatabaseConnectionTest" time="0.607"/>
  <testcase name="deve criar uma instância Sql válida" classname="groovy.database.DatabaseConnectionTest" time="0.158"/>
  <testcase name="deve lançar exceção quando não conseguir conectar ao banco" classname="groovy.database.DatabaseConnectionTest" time="0.412"/>
  <system-out><![CDATA[Erro ao criar conexão: FATAL: password authentication failed for user "usuario_invalido"
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
